function x = multiscaleRecon(bands)
% Inverse Haar wavelet transform 
% IN:
%   bands: cell array of wavelet bands
% OUT:
%   x: image
%
% The Software does not have 510K approval,  U.S. Food and Drug Administration (FDA) clearance,
% European Medicines Agency (EMA) clearance or CE mark. The Software is intended research purposes only,
% not for diagnostic or clinical use.
%
% Copyright (C) 2019  Charles Millard
% Copyright (C) 2019  Siemens Healthineers

    scales = numel(bands);
    
    x = idwt2( ...
        bands{scales}.A, ...
        bands{scales}.H, ...
        bands{scales}.V, ...
        bands{scales}.D, ...
        'haar');
    
    for s = scales-1:-1:1
        x = idwt2( ...
            x, ...
            bands{s}.H, ...
            bands{s}.V, ...
            bands{s}.D, ...
            'haar');
    end
end