function bands = pyramidInv(img, scales)
    %UNTITLED11 Summary of this function goes here
    %   Detailed explanation goes here
    
    bands = cell(scales, 1);
    
    for s = 1:scales-1
        bands{s} = struct( ...
            'H', img(1:end/2, end/2+1:end), ...
            'V', img(end/2+1:end, 1:end/2), ...
            'D', img(end/2+1:end, end/2+1:end));
        img = img(1:end/2, 1:end/2);
    end
    
    bands{scales} = struct( ...
        'A', img(1:end/2, 1:end/2), ...
        'H', img(1:end/2, end/2+1:end), ...
        'V', img(end/2+1:end, 1:end/2), ...
        'D', img(end/2+1:end, end/2+1:end));
end

